### ISSUE TITLE
Consider to use object instead of T : class

### ISSUE THREAD

**Issue by ozantopal** [PeakUp/PeakUp.Utilities#1]
In FunctionalHepler [class](https://github.com/PeakUp/PeakUp.Utilities/blob/0eddc5e0e040f185bd62bc73d93f15596ad5a50d/PeakUp.Utilities/FunctionalExtensions.cs#L19), usage of T : class, a.k.a generic param, has its limitation such as forcing T to be a class which is that must be a reference type. I haven't realized any benefit to use of it. On the other hands if you prefer to use object you can extend value types such as int?(nullable integer) and etc. 

You can see below what I suggest:
`public static bool IsNull(this object self) => self == null;`

P.S: It makes me feel that this class advance readability of the code basically and this has a good motivation to use this extension method, but writing a method for null check makes me also consider about inside of that method.

**Comment by fthdgn-gh** [comment]
Hi Ozan, sorry for the late response and thanks for the issue and pull request. I wanted to explain the reasoning behind the usage of generics and addition of the constraint to make this method only accessible to the classes. I will also try to propose a solution for your Nullable suggestion.

As you may know, only the reference types are capable of being null. This is the main reason why we made this method generic and added a constraint to make it accept only reference types. About why we didn't consider this method to accept an object is actually making a parameter or return type an object, opens up a possibility of unintended boxing and unboxing operations.

But as you pointed out, constraining the method to only accept reference types causes us to miss a useful approach when we try to use this method on a Nullable type. Thank you for noticing and deciding to give us a feedback about it.

After thinking and arguing about it in our team, we decided to add an another overload to this method to support Nullable types. We will update the repository and NuGet packages with the addition of this method and couple other things unrelated to this issue.

I will keep here posted.

We are eager to hear more feedback like these, so thanks again.

**Comment by fthdgn-gh** [comment]
As I mentioned in the PR, I'm closing this issue too.
